In [2]:
import pandas as pd 
df=pd.read_csv('spam.csv') 
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [5]:
df.head(
    
)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [7]:
X_train.shape

(4457,)

In [8]:
type(y_train)

pandas.core.series.Series

In [9]:
y_train[:4]

3852    0
2692    0
568     0
2020    0
Name: spam, dtype: int64

In [10]:
   
type(X_train.values)

numpy.ndarray

In [11]:

from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59070 stored elements and shape (4457, 7740)>

In [12]:
X_train_cv.toarray()[:5][0]

array([0, 0, 0, ..., 0, 0, 0])

In [13]:

X_train_cv.shape

(4457, 7740)

In [14]:
y_train.shape

(4457,)

In [15]:

v.get_feature_names_out()[1001]

'aphex'

In [16]:
v.vocabulary_

{'we': 7409,
 'have': 3338,
 'all': 902,
 'rounder': 5818,
 'so': 6270,
 'not': 4819,
 'required': 5716,
 'hey': 3404,
 'tmr': 6910,
 'meet': 4410,
 'at': 1105,
 'bugis': 1548,
 '930': 716,
 'anyways': 994,
 'you': 7701,
 'can': 1623,
 'just': 3857,
 'go': 3141,
 'to': 6916,
 'your': 7706,
 'gym': 3265,
 'or': 4970,
 'whatever': 7469,
 'my': 4649,
 'love': 4209,
 'smiles': 6241,
 'hope': 3472,
 'ok': 4908,
 'and': 951,
 'having': 3344,
 'good': 3165,
 'day': 2163,
 'babe': 1178,
 'miss': 4496,
 'much': 4616,
 'already': 913,
 'from': 2998,
 'tomorrow': 6945,
 'onwards': 4944,
 'eve': 2635,
 'work': 7589,
 'wishing': 7540,
 'family': 2749,
 'merry': 4440,
 'mas': 4354,
 'happy': 3315,
 'new': 4745,
 'year': 7676,
 'in': 3623,
 'advance': 823,
 'are': 1036,
 'coming': 1895,
 'for': 2919,
 'class': 1817,
 'okie': 4913,
 'swt': 6650,
 'thought': 6849,
 'nver': 4853,
 'get': 3096,
 'tired': 6892,
 'of': 4884,
 'doing': 2382,
 'little': 4134,
 'things': 6831,
 'lovable': 4208,
 'persons': 51

In [17]:
import numpy as np 

In [18]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [19]:
np.where(X_train_np[1]!=0)

(array([ 716, 1105, 1548, 3404, 4410, 6910]),)

In [20]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [21]:
x_test_cv=v.transform(X_test)

In [22]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       959
           1       0.95      0.94      0.94       156

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



Here we can see how we can perform the same operation using pipeline 


In [24]:

from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [25]:

clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [26]:

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       959
           1       0.95      0.94      0.94       156

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115

